export const services = [
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "2300 USD",
    status: "Active",
    taskName: "Research cleanpaste",
    date: "22.02.19",
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1980 USD",
    status: "Passive",
    taskName: "Toothpaste research",
    date: "22.02.19",
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1900 USD",
    status: "Active",
    taskName: "Research toothpaste",
    date: "22.02.19",
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "2300 USD",
    status: "Active",
    taskName: "Research cleanpaste",
    date: "22.02.19",
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1980 USD",
    status: "Passive",
    taskName: "Toothpaste research",
    date: "22.02.19",
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1900 USD",
    status: "Active",
    taskName: "Research toothpaste",
    date: "22.02.19",
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "2300 USD",
    status: "Active",
    taskName: "Research cleanpaste",
    date: "22.02.19",
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1980 USD",
    status: "Passive",
    taskName: "Toothpaste research",
    date: "22.02.19",
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1900 USD",
    status: "Active",
    taskName: "Research toothpaste",
    date: "22.02.19",
  },
];
