export const services = [
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "2300 USD",
    status: "Active",
    taskName: "Research",
    date: "22.02.19",
    id: 1,
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1980 USD",
    status: "Passive",
    taskName: "Toothpaste research",
    date: "22.02.19",
    id: 2,
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1900 USD",
    status: "Active",
    taskName: "Research toothpaste",
    date: "22.02.19",
    id: 3,
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "2300 USD",
    status: "Active",
    taskName: "Cleanpaste",
    date: "22.02.19",
    id: 4,
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1980 USD",
    status: "Passive",
    taskName: "Tooth research",
    date: "22.02.19",
    id: 5,
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1900 USD",
    status: "Active",
    taskName: "Research tooth",
    date: "22.02.19",
    id: 6,
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "2300 USD",
    status: "Active",
    taskName: "Research cleanpaste",
    date: "22.02.19",
    id: 7,
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1980 USD",
    status: "Passive",
    taskName: "Toothpastere",
    date: "22.02.19",
    id: 8,
  },
  {
    customer: "OOO Procter&Gamble",
    executor: "Techservice",
    price: "1900 USD",
    status: "Active",
    taskName: "Res toothpaste",
    date: "22.02.19",
    id: 9,
  },
];
